version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog_db
      MYSQL_USER: root_user
      MYSQL_PASSWORD: root_password
    ports:
      - "9906:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  php:
    container_name: php-container
    build:
      context: ./src
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/html/src

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql
volumes:
  mysql_data:
    # driver: local

